import Head from 'next/head';
// import Layout, { siteTitle } from '../components/layout';
// import utilStyles from '../styles/utils.module.css';
import Hero from '../components/Hero';
import Footer from '../components/footer';

export default function Home() {
  return (
    // <Layout home>
    <div>
      <Head>
        <title>Present Tense Marketing</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Hero heading='Present Tense Marketing' message='Tagline- The Moment is NOW! or Be your best in the present so your
      future is limitless!'/>
      <Footer/>
    </div>
   
  );
}